Add "Member left" message
TeamOctolings/Octobot pull request #234
Opened 2023-12-19 13:25 UTC by mctaylors

Closes #231

2023-12-20 16:09 UTC, Octol1ttle commented on src/Data/GuildSettings.cs
> +    ///     Controls what message should be sent in <see cref="PublicFeedbackChannel" /> when member leaves the server.
```suggestion
    ///     Controls what message should be sent in <see cref="PublicFeedbackChannel" /> when a member leaves the guild.
```

2023-12-20 16:09 UTC, Octol1ttle commented on src/Messages.Designer.cs
> +        }
Unused

2023-12-20 17:34 UTC, Octol1ttle commented on src/Data/GuildSettings.cs
> +    ///         <item><see cref="Messages.DefaultLeaveMessage" /> will be sent if set to "default" or "reset"</item>
```suggestion
    ///         <item><see cref="Messages.DefaultLeaveMessage" /> will be sent if set to "default" or "reset".</item>
```

2023-12-20 17:34 UTC, Octol1ttle commented on src/Responders/GuildMemberLeftResponder.cs
> +public class GuildMemberLeftResponder : IResponder<IGuildMemberRemove>
this will also trigger when a member is banned/kicked, do we want the leave message to display in that case?

2023-12-20 17:35 UTC, mctaylors commented on src/Data/GuildSettings.cs
> +    ///         <item><see cref="Messages.DefaultLeaveMessage" /> will be sent if set to "default" or "reset"</item>
oh my god

2023-12-20 18:01 UTC, mctaylors commented on src/Responders/GuildMemberLeftResponder.cs
> +public class GuildMemberLeftResponder : IResponder<IGuildMemberRemove>
> this will also trigger when a member is banned/kicked, do we want the leave message to display in that case?

At this time, it is not possible to keep track of kicked users. Will be resolved in #241

2023-12-20 21:10 UTC, mctaylors commented
Will be unblocked after merging #242

2023-12-21 15:43 UTC, Octol1ttle requested changes

2023-12-21 15:43 UTC, Octol1ttle commented on locale/Messages.resx
> +  <data name="DefaultLeaveMessage" xml:space="preserve">
woops

2023-12-21 15:44 UTC, mctaylors commented on locale/Messages.resx
> +  <data name="DefaultLeaveMessage" xml:space="preserve">
ik

2023-12-21 15:55 UTC, Octol1ttle commented on src/Responders/GuildMemberLeftResponder.cs
> +        }
merge `if` statements

2023-12-21 16:05 UTC, Octol1ttle requested changes

2023-12-21 16:05 UTC, Octol1ttle commented on src/Responders/GuildMemberLeftResponder.cs
> +        Thread.Sleep(1000);
Do not use `Thread#Sleep`, use `Task#Delay` instead

2023-12-21 16:05 UTC, Octol1ttle commented on src/Responders/GuildMemberLeftResponder.cs
> +        if (memberData.BannedUntil is not null && memberData.Kicked)
This condition requires that the user is both banned *and* kicked, which is impossible.

2023-12-21 16:06 UTC, mctaylors commented on src/Responders/GuildMemberLeftResponder.cs
> +        if (memberData.BannedUntil is not null && memberData.Kicked)
wow, I didn't even notice that when I was coding this.

2023-12-21 16:11 UTC, Octol1ttle requested changes

2023-12-21 16:11 UTC, Octol1ttle commented on src/Responders/GuildMemberLeftResponder.cs
> +        await Task.Delay(1000, ct);
This is grounds for rejecting this pull request. With the addition of the profiler coming our way, this will inevitably trip the warning. Given that the comment below indicates that you have no other solution, I'll try to investigate this issue when I'm able. If no good solution can be agreed upon, this will be closed.

2024-03-18 12:28 UTC, mctaylors commented
After such a long time, I've already forgotten the reason of the race condition. Cool.

2024-03-20 09:15 UTC, Octol1ttle approved these changes

2024-03-20 11:18 UTC, merged