Add /8ball command
TeamOctolings/Octobot pull request #264
Opened 2024-03-09 21:48 UTC by mctaylors

@neroduckale was bored so I made this feature.

2024-03-10 19:31 UTC, Apceniy commented
Why are the answers in tt-ru locale ordered this way?

2024-03-10 19:36 UTC, mctaylors commented
> Why are the answers in tt-ru locale ordered this way?

`mctaylors-ru`, to be correct. It's my language and I translate it as I wish. If I'm happy with the translation, then that's the way it's going to be *or until the maintainer himself says so*.

2024-03-12 15:33 UTC, Octol1ttle requested changes

2024-03-12 15:33 UTC, Octol1ttle commented on locale/Messages.ru.resx
> +      <value>Сконцентрируйся и спроси опять</value>
```suggestion
      <value>Сконцентрируйся и спроси снова</value>
```

2024-03-12 15:33 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    [Description("Ask a question to")]
Ask a question to... what?

2024-03-12 15:33 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +            _ => ColorsList.Default
Should throw instead, indexes other than 0-3 will lead to an IndexOutOfBoundsException

2024-03-13 14:53 UTC, Octol1ttle requested changes

2024-03-13 14:53 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    ///     A slash command that shows a random magic 8-ball's answer.
```suggestion
    ///     A slash command that shows a random answer from the Magic 8-Ball.
```

2024-03-13 14:53 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    ///     A feedback sending result which may have succeeded.
```suggestion
    ///     A feedback sending result which may or may not have succeeded.
```

2024-03-13 14:53 UTC, Octol1ttle commented on src/Commands/ToolsCommandGroup.cs
> +    [Description("Ask the magic 8-ball a question")]
```suggestion
    [Description("Ask the Magic 8-Ball a question")]
```

2024-03-13 17:40 UTC, Octol1ttle approved these changes

2024-03-13 17:40 UTC, merged