Don't hardcode logo's link in /about
TeamOctolings/Octobot pull request #301
Opened 2024-04-07 12:55 UTC by mctaylors

In this PR, I made the link in /about "dynamic" and now it also depends on the value in BuildInfo.Branch.

Blocked by #300, use of BuildInfo.RepositoryAuthor and BuildInfo.RepositoryName depends on this PR.

2024-04-07 13:13 UTC, Octol1ttle requested changes

2024-04-07 13:13 UTC, Octol1ttle commented on src/Commands/AboutCommandGroup.cs
> +            .WithImageUrl($"https://raw.githubusercontent.com/TeamOctolings/Octobot/{BuildInfo.Branch}/docs/octobot-banner.png")
```suggestion
            .WithImageUrl("https://raw.githubusercontent.com/TeamOctolings/Octobot/HEAD/docs/octobot-banner.png")
```

2024-04-08 11:01 UTC, Octol1ttle approved these changes
"*I* made" lmao

2024-04-08 11:01 UTC, mctaylors commented
> "_I_ made" lmao

bruh

2024-04-08 11:02 UTC, merged